[package]
name = "luafmt-lib"
version = "0.1.0"
authors = ["JohnnyMorganz <therobloxbot@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
full_moon = "0.7.0"
